module.exports = {

    Icons: {

        AppIcon: require('../Icons/App.png'),
        contact: require('../Icons/contact.png'),
        lock: require('../Icons/lock.png'),
        star: require('../Icons/star.png'),
        ShareIcon: require('../Icons/ShareIcon.png'),
        refresh: require('../Icons/refresh.png'),
        premium_quality: require('../Icons/diamond.png'),
        comment: require('../Icons/comment.jpg'),
        Earn: require('../Icons/Earn.jpg'),
        purchase: require('../Icons/purchase.png'),
        AddFL: require('../Icons/AddFL.jpg'),
        shareHome: require('../Icons/share.jpg'),
        menu: require('../Icons/menu.png'),
        logout: require('../Icons/logout.png'),
        Like: require('../Icons/Like.png'),
        Back: require('../Icons/Back.png'),
        Group: require('../Icons/Group.png'),
        follow: require('../Icons/follow.png'),
        get_follower: require('../Icons/get_follower.png'),
        follower_list: require('../Icons/follower_list.png'),
        Like_List: require('../Icons/Like_List.jpg'),
        Video: require('../Icons/Video.png'),
        CommentList: require('../Icons/CommentList.jpg'),
        GetComments:require('../Icons/GetComments.png'),
        right:require('../Icons/right.png'),
        ShareList:require('../Icons/ShareList.jpg'),
        Share1:require('../Icons/Share1.png'),
        Video1:require('../Icons/VideoX.jpg'),
        Scatch:require('../Icons/Scatch.jpg'),
        doFL:require('../Icons/doFL.jpg'),
        watch:require('../Icons/watch.png'),
        whiteVideo:require('../Icons/whiteVideo.jpg'),
        mobile:require('../Icons/mobile.jpg'),
        PinkDM:require('../Icons/PinkDM.png'),
        heartWhite:require('../Icons/heartWhite.png'),
        polo:require('../Icons/polo.png'),
        sad:require('../Icons/sad.png'),
        thumbnail:require('../Icons/thumb.png'),
        usd_selected:require('../Icons/usd_selected.png'),
        usd_unselected:require('../Icons/usd_unselected.png'),
        inr_selected:require('../Icons/inr_selected.png'),
        inr_unselected:require('../Icons/inr_unselected.png'),
        doView:require('../Icons/doView.png'),
        ViewList:require('../Icons/ViewList.png'),
        googlepayunselected:require('../Icons/googlepayunselected.png'),
        googlepayselected:require('../Icons/googlepayselected.png'),
        ScratchImage:require('../Icons/ScratchImage.jpg'),
        gift:require('../Icons/gift.jpg'),
        Newdmd:require('../Icons/Newdmd.jpg'),
        close:require('../Icons/close.png')
    }


}